# Set-up
sudo: false

language: c

# Cache builds
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# Build matrix configuration
matrix:
  include:
  - env: RESOLVER="nightly"
    addons: {apt: {packages: [libgmp-dev]}}

# Download and unpack the stack executable
before_install:
- export PATH=/opt/ghc/$GHCVER/bin:$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Test build
script:
- stack --no-terminal --install-ghc --resolver=$RESOLVER build
